// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementpb/mysql.proto

package managementpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	inventorypb "github.com/percona/pmm/api/inventorypb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMySQLRequest struct {
	// Node identifier on which a service is been running.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Node name on which a service is been running.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Create a new Node with those parameters.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	AddNode *AddNodeParams `protobuf:"bytes,3,opt,name=add_node,json=addNode,proto3" json:"add_node,omitempty"`
	// Unique across all Services user-defined name. Required.
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Node and Service access address (DNS name or IP).
	// Address (and port) or socket is required.
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// Service Access port.
	// Port is required when the address present.
	Port uint32 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	// Service Access socket.
	// Address (and port) or socket is required.
	Socket string `protobuf:"bytes,22,opt,name=socket,proto3" json:"socket,omitempty"`
	// The "pmm-agent" identifier which should run agents. Required.
	PmmAgentId string `protobuf:"bytes,7,opt,name=pmm_agent_id,json=pmmAgentId,proto3" json:"pmm_agent_id,omitempty"`
	// Environment name.
	Environment string `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	// Cluster name.
	Cluster string `protobuf:"bytes,9,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Replication set name.
	ReplicationSet string `protobuf:"bytes,10,opt,name=replication_set,json=replicationSet,proto3" json:"replication_set,omitempty"`
	// MySQL username for scraping metrics.
	Username string `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	// MySQL password for scraping metrics.
	Password string `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	// If true, adds qan-mysql-perfschema-agent for provided service.
	QanMysqlPerfschema bool `protobuf:"varint,13,opt,name=qan_mysql_perfschema,json=qanMysqlPerfschema,proto3" json:"qan_mysql_perfschema,omitempty"`
	// If true, adds qan-mysql-slowlog-agent for provided service.
	QanMysqlSlowlog bool `protobuf:"varint,14,opt,name=qan_mysql_slowlog,json=qanMysqlSlowlog,proto3" json:"qan_mysql_slowlog,omitempty"`
	// Custom user-assigned labels for Service.
	CustomLabels map[string]string `protobuf:"bytes,15,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Skip connection check.
	SkipConnectionCheck bool `protobuf:"varint,16,opt,name=skip_connection_check,json=skipConnectionCheck,proto3" json:"skip_connection_check,omitempty"`
	// Disable query examples.
	DisableQueryExamples bool `protobuf:"varint,17,opt,name=disable_query_examples,json=disableQueryExamples,proto3" json:"disable_query_examples,omitempty"`
	// If qan-mysql-slowlog-agent is added, slowlog file is rotated at this size if > 0.
	// If zero, server's default value is used.
	// Use negative value to disable rotation.
	MaxSlowlogFileSize int64 `protobuf:"varint,18,opt,name=max_slowlog_file_size,json=maxSlowlogFileSize,proto3" json:"max_slowlog_file_size,omitempty"`
	// Use TLS for database connections.
	Tls bool `protobuf:"varint,19,opt,name=tls,proto3" json:"tls,omitempty"`
	// Skip TLS certificate and hostname validation.
	TlsSkipVerify bool `protobuf:"varint,20,opt,name=tls_skip_verify,json=tlsSkipVerify,proto3" json:"tls_skip_verify,omitempty"`
	// Tablestats group collectors will be disabled if there are more than that number of tables.
	// If zero, server's default value is used.
	// Use negative value to disable them.
	TablestatsGroupTableLimit int32 `protobuf:"varint,21,opt,name=tablestats_group_table_limit,json=tablestatsGroupTableLimit,proto3" json:"tablestats_group_table_limit,omitempty"`
	// enables push model at exporter
	PushModelEnabled     bool     `protobuf:"varint,23,opt,name=push_model_enabled,json=pushModelEnabled,proto3" json:"push_model_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMySQLRequest) Reset()         { *m = AddMySQLRequest{} }
func (m *AddMySQLRequest) String() string { return proto.CompactTextString(m) }
func (*AddMySQLRequest) ProtoMessage()    {}
func (*AddMySQLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81470951176953, []int{0}
}

func (m *AddMySQLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLRequest.Unmarshal(m, b)
}
func (m *AddMySQLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLRequest.Marshal(b, m, deterministic)
}
func (m *AddMySQLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLRequest.Merge(m, src)
}
func (m *AddMySQLRequest) XXX_Size() int {
	return xxx_messageInfo_AddMySQLRequest.Size(m)
}
func (m *AddMySQLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLRequest proto.InternalMessageInfo

func (m *AddMySQLRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddMySQLRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *AddMySQLRequest) GetAddNode() *AddNodeParams {
	if m != nil {
		return m.AddNode
	}
	return nil
}

func (m *AddMySQLRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *AddMySQLRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddMySQLRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AddMySQLRequest) GetSocket() string {
	if m != nil {
		return m.Socket
	}
	return ""
}

func (m *AddMySQLRequest) GetPmmAgentId() string {
	if m != nil {
		return m.PmmAgentId
	}
	return ""
}

func (m *AddMySQLRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *AddMySQLRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *AddMySQLRequest) GetReplicationSet() string {
	if m != nil {
		return m.ReplicationSet
	}
	return ""
}

func (m *AddMySQLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddMySQLRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddMySQLRequest) GetQanMysqlPerfschema() bool {
	if m != nil {
		return m.QanMysqlPerfschema
	}
	return false
}

func (m *AddMySQLRequest) GetQanMysqlSlowlog() bool {
	if m != nil {
		return m.QanMysqlSlowlog
	}
	return false
}

func (m *AddMySQLRequest) GetCustomLabels() map[string]string {
	if m != nil {
		return m.CustomLabels
	}
	return nil
}

func (m *AddMySQLRequest) GetSkipConnectionCheck() bool {
	if m != nil {
		return m.SkipConnectionCheck
	}
	return false
}

func (m *AddMySQLRequest) GetDisableQueryExamples() bool {
	if m != nil {
		return m.DisableQueryExamples
	}
	return false
}

func (m *AddMySQLRequest) GetMaxSlowlogFileSize() int64 {
	if m != nil {
		return m.MaxSlowlogFileSize
	}
	return 0
}

func (m *AddMySQLRequest) GetTls() bool {
	if m != nil {
		return m.Tls
	}
	return false
}

func (m *AddMySQLRequest) GetTlsSkipVerify() bool {
	if m != nil {
		return m.TlsSkipVerify
	}
	return false
}

func (m *AddMySQLRequest) GetTablestatsGroupTableLimit() int32 {
	if m != nil {
		return m.TablestatsGroupTableLimit
	}
	return 0
}

func (m *AddMySQLRequest) GetPushModelEnabled() bool {
	if m != nil {
		return m.PushModelEnabled
	}
	return false
}

type AddMySQLResponse struct {
	Service            *inventorypb.MySQLService            `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	MysqldExporter     *inventorypb.MySQLdExporter          `protobuf:"bytes,2,opt,name=mysqld_exporter,json=mysqldExporter,proto3" json:"mysqld_exporter,omitempty"`
	QanMysqlPerfschema *inventorypb.QANMySQLPerfSchemaAgent `protobuf:"bytes,3,opt,name=qan_mysql_perfschema,json=qanMysqlPerfschema,proto3" json:"qan_mysql_perfschema,omitempty"`
	QanMysqlSlowlog    *inventorypb.QANMySQLSlowlogAgent    `protobuf:"bytes,4,opt,name=qan_mysql_slowlog,json=qanMysqlSlowlog,proto3" json:"qan_mysql_slowlog,omitempty"`
	// Actual table count at the moment of adding.
	TableCount           int32    `protobuf:"varint,5,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMySQLResponse) Reset()         { *m = AddMySQLResponse{} }
func (m *AddMySQLResponse) String() string { return proto.CompactTextString(m) }
func (*AddMySQLResponse) ProtoMessage()    {}
func (*AddMySQLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab81470951176953, []int{1}
}

func (m *AddMySQLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMySQLResponse.Unmarshal(m, b)
}
func (m *AddMySQLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMySQLResponse.Marshal(b, m, deterministic)
}
func (m *AddMySQLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMySQLResponse.Merge(m, src)
}
func (m *AddMySQLResponse) XXX_Size() int {
	return xxx_messageInfo_AddMySQLResponse.Size(m)
}
func (m *AddMySQLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMySQLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddMySQLResponse proto.InternalMessageInfo

func (m *AddMySQLResponse) GetService() *inventorypb.MySQLService {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *AddMySQLResponse) GetMysqldExporter() *inventorypb.MySQLdExporter {
	if m != nil {
		return m.MysqldExporter
	}
	return nil
}

func (m *AddMySQLResponse) GetQanMysqlPerfschema() *inventorypb.QANMySQLPerfSchemaAgent {
	if m != nil {
		return m.QanMysqlPerfschema
	}
	return nil
}

func (m *AddMySQLResponse) GetQanMysqlSlowlog() *inventorypb.QANMySQLSlowlogAgent {
	if m != nil {
		return m.QanMysqlSlowlog
	}
	return nil
}

func (m *AddMySQLResponse) GetTableCount() int32 {
	if m != nil {
		return m.TableCount
	}
	return 0
}

func init() {
	proto.RegisterType((*AddMySQLRequest)(nil), "management.AddMySQLRequest")
	proto.RegisterMapType((map[string]string)(nil), "management.AddMySQLRequest.CustomLabelsEntry")
	proto.RegisterType((*AddMySQLResponse)(nil), "management.AddMySQLResponse")
}

func init() {
	proto.RegisterFile("managementpb/mysql.proto", fileDescriptor_ab81470951176953)
}

var fileDescriptor_ab81470951176953 = []byte{
	// 907 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdd, 0x6e, 0x23, 0x35,
	0x14, 0xc7, 0x35, 0xed, 0xe6, 0xa3, 0x4e, 0xda, 0xb4, 0xde, 0x7e, 0x78, 0xb3, 0x45, 0x8d, 0x82,
	0x04, 0x61, 0x45, 0x33, 0x34, 0xac, 0x10, 0xda, 0x9b, 0x55, 0x5a, 0x15, 0xb4, 0xa2, 0xad, 0xb6,
	0x93, 0x15, 0x42, 0xdc, 0x8c, 0x9c, 0xf1, 0x69, 0x6a, 0x32, 0xb6, 0x27, 0x63, 0x4f, 0xda, 0xec,
	0x25, 0xaf, 0xc0, 0x73, 0x71, 0xc5, 0x03, 0x20, 0x21, 0x9e, 0x81, 0x6b, 0x64, 0xcf, 0xe4, 0xa3,
	0xbb, 0x85, 0x3b, 0x9f, 0xf3, 0xfb, 0xfb, 0xf8, 0x1c, 0xfb, 0x1c, 0x23, 0x22, 0xa8, 0xa4, 0x23,
	0x10, 0x20, 0x4d, 0x32, 0xf4, 0xc5, 0x4c, 0x4f, 0xe2, 0x6e, 0x92, 0x2a, 0xa3, 0x30, 0x5a, 0x92,
	0xe6, 0x37, 0x23, 0x6e, 0x6e, 0xb3, 0x61, 0x37, 0x52, 0xc2, 0x17, 0x77, 0xdc, 0x8c, 0xd5, 0x9d,
	0x3f, 0x52, 0xc7, 0x4e, 0x78, 0x3c, 0xa5, 0x31, 0x67, 0xd4, 0xa8, 0x54, 0xfb, 0x8b, 0x65, 0x1e,
	0xa3, 0x79, 0x38, 0x52, 0x6a, 0x14, 0x83, 0x4f, 0x13, 0xee, 0x53, 0x29, 0x95, 0xa1, 0x86, 0x2b,
	0xa9, 0x0b, 0x4a, 0xb8, 0x9c, 0x82, 0x34, 0x2a, 0x9d, 0x25, 0x43, 0x9f, 0x8e, 0x40, 0x9a, 0x39,
	0x69, 0xae, 0x12, 0x0d, 0xe9, 0x94, 0x47, 0xb0, 0x60, 0x0f, 0x32, 0x2e, 0x60, 0xce, 0xda, 0xff,
	0x54, 0x50, 0xa3, 0xcf, 0xd8, 0xe5, 0x6c, 0x70, 0x7d, 0x11, 0xc0, 0x24, 0x03, 0x6d, 0xf0, 0x01,
	0xaa, 0x48, 0xc5, 0x20, 0xe4, 0x8c, 0x78, 0x2d, 0xaf, 0xb3, 0x11, 0x94, 0xad, 0xf9, 0x86, 0xe1,
	0xe7, 0x68, 0xc3, 0x01, 0x49, 0x05, 0x90, 0x35, 0x87, 0xaa, 0xd6, 0x71, 0x45, 0x05, 0xe0, 0x97,
	0xa8, 0x4a, 0x19, 0x0b, 0xad, 0x4d, 0xd6, 0x5b, 0x5e, 0xa7, 0xd6, 0x7b, 0xd6, 0x5d, 0x1e, 0xdc,
	0xed, 0x33, 0x76, 0xa5, 0x18, 0xbc, 0xa5, 0x29, 0x15, 0x3a, 0xa8, 0xd0, 0xdc, 0xc4, 0x5f, 0xa0,
	0x7a, 0x91, 0x50, 0x1e, 0xf5, 0x89, 0x8d, 0x7a, 0x5a, 0xfe, 0xeb, 0xcf, 0xa3, 0xb5, 0x9f, 0xbc,
	0xa0, 0x56, 0x30, 0x77, 0x00, 0x41, 0x76, 0x57, 0x0a, 0x5a, 0x93, 0x92, 0x3b, 0x7b, 0x6e, 0x62,
	0x8c, 0x9e, 0x24, 0x2a, 0x35, 0xa4, 0xdc, 0xf2, 0x3a, 0x9b, 0x81, 0x5b, 0xe3, 0x7d, 0x54, 0xd6,
	0x2a, 0x1a, 0x83, 0x21, 0xfb, 0x79, 0x0d, 0xb9, 0x85, 0x3b, 0xa8, 0x9e, 0x08, 0x11, 0xba, 0xcb,
	0xb3, 0x15, 0x56, 0x1e, 0x1c, 0x88, 0x12, 0x21, 0xfa, 0x16, 0xbd, 0x61, 0xb8, 0x85, 0x6a, 0x20,
	0xa7, 0x3c, 0x55, 0xd2, 0x16, 0x40, 0xaa, 0x2e, 0xcc, 0xaa, 0xcb, 0x66, 0x14, 0xc5, 0x99, 0x36,
	0x90, 0x92, 0x8d, 0x3c, 0xa3, 0xc2, 0xc4, 0x9f, 0xa3, 0x46, 0x0a, 0x49, 0xcc, 0x23, 0xf7, 0x7c,
	0xa1, 0x06, 0x43, 0x90, 0x53, 0x6c, 0xad, 0xb8, 0x07, 0x60, 0x70, 0x1b, 0x55, 0x33, 0x0d, 0xa9,
	0xab, 0xbd, 0xf6, 0x20, 0x95, 0x85, 0x1f, 0x37, 0x51, 0x35, 0xa1, 0x5a, 0xdf, 0xa9, 0x94, 0x91,
	0x7a, 0x7e, 0xeb, 0x73, 0x1b, 0x7f, 0x85, 0x76, 0x27, 0x54, 0x86, 0xae, 0x0d, 0xc3, 0x04, 0xd2,
	0x1b, 0x1d, 0xdd, 0x82, 0xa0, 0x64, 0xb3, 0xe5, 0x75, 0xaa, 0x01, 0x9e, 0x50, 0x79, 0x69, 0xd1,
	0xdb, 0x05, 0xc1, 0x2f, 0xd0, 0xce, 0x72, 0x87, 0x8e, 0xd5, 0x5d, 0xac, 0x46, 0x64, 0xcb, 0xc9,
	0x1b, 0x73, 0xf9, 0x20, 0x77, 0xe3, 0x00, 0x6d, 0x46, 0x99, 0x36, 0x4a, 0x84, 0x31, 0x1d, 0x42,
	0xac, 0x49, 0xa3, 0xb5, 0xde, 0xa9, 0xf5, 0x8e, 0x3f, 0x78, 0xd8, 0xd5, 0xee, 0xe9, 0x9e, 0xb9,
	0x0d, 0x17, 0x4e, 0x7f, 0x2e, 0x4d, 0x3a, 0x0b, 0xea, 0xd1, 0x8a, 0x0b, 0xf7, 0xd0, 0x9e, 0x1e,
	0xf3, 0x24, 0x8c, 0x94, 0x94, 0x10, 0xb9, 0xeb, 0x89, 0x6e, 0x21, 0x1a, 0x93, 0x6d, 0x97, 0xc3,
	0x53, 0x0b, 0xcf, 0x16, 0xec, 0xcc, 0x22, 0xfc, 0x12, 0xed, 0x33, 0xae, 0xe9, 0x30, 0x86, 0x70,
	0x92, 0x41, 0x3a, 0x0b, 0xe1, 0x9e, 0x8a, 0x24, 0x06, 0x4d, 0x76, 0xdc, 0xa6, 0xdd, 0x82, 0x5e,
	0x5b, 0x78, 0x5e, 0x30, 0x7c, 0x82, 0xf6, 0x04, 0xbd, 0x9f, 0xd7, 0x18, 0xde, 0xf0, 0x18, 0x42,
	0xcd, 0xdf, 0x03, 0xc1, 0x2d, 0xaf, 0xb3, 0x1e, 0x60, 0x41, 0xef, 0x8b, 0x42, 0xbf, 0xe3, 0x31,
	0x0c, 0xf8, 0x7b, 0xc0, 0xdb, 0x68, 0xdd, 0xc4, 0x9a, 0x3c, 0x75, 0x51, 0xed, 0x12, 0x7f, 0x86,
	0x1a, 0x26, 0xd6, 0xa1, 0x4b, 0x79, 0x0a, 0x29, 0xbf, 0x99, 0x91, 0x5d, 0x47, 0x37, 0x4d, 0xac,
	0x07, 0x63, 0x9e, 0xfc, 0xe8, 0x9c, 0xf8, 0x35, 0x3a, 0x34, 0x36, 0x05, 0x6d, 0xa8, 0xd1, 0xe1,
	0x28, 0x55, 0x59, 0x12, 0x3a, 0x47, 0x18, 0x73, 0xc1, 0x0d, 0xd9, 0x6b, 0x79, 0x9d, 0x52, 0xf0,
	0x6c, 0xa9, 0xf9, 0xde, 0x4a, 0xde, 0x59, 0xf3, 0xc2, 0x0a, 0xf0, 0x97, 0x08, 0x27, 0x99, 0xbe,
	0x0d, 0x85, 0x62, 0x10, 0x87, 0x20, 0x2d, 0x61, 0xe4, 0xc0, 0x9d, 0xb5, 0x6d, 0xc9, 0xa5, 0x05,
	0xe7, 0xb9, 0xbf, 0xf9, 0x1a, 0xed, 0x7c, 0x74, 0xd1, 0x36, 0xfb, 0x31, 0xcc, 0x8a, 0xa1, 0xb5,
	0x4b, 0xbc, 0x8b, 0x4a, 0x53, 0x1a, 0x67, 0xf3, 0x69, 0xcd, 0x8d, 0x57, 0x6b, 0xdf, 0x7a, 0xed,
	0xdf, 0xd7, 0xd0, 0xf6, 0xf2, 0xe9, 0x74, 0xa2, 0xa4, 0x06, 0x7c, 0x82, 0x2a, 0xc5, 0xc4, 0xb9,
	0x20, 0xb5, 0xde, 0x41, 0x77, 0xf1, 0xaf, 0x74, 0x9d, 0x74, 0x90, 0xe3, 0x60, 0xae, 0xc3, 0xa7,
	0xa8, 0xe1, 0x5a, 0x89, 0x85, 0x70, 0x6f, 0x07, 0x0f, 0x52, 0x77, 0x96, 0x9d, 0xfe, 0x0f, 0xb6,
	0xb2, 0xf3, 0x42, 0x10, 0x6c, 0xe5, 0x3b, 0xe6, 0x36, 0x7e, 0xf7, 0x1f, 0x4d, 0x9c, 0x7f, 0x23,
	0xed, 0x95, 0x40, 0xd7, 0xfd, 0x2b, 0x17, 0xcb, 0xf6, 0xf3, 0xc0, 0x89, 0xdc, 0xb4, 0x3e, 0xda,
	0xe8, 0x3f, 0x3c, 0xd6, 0xe8, 0x4f, 0x5c, 0xc8, 0xa3, 0x47, 0x42, 0x16, 0xad, 0x90, 0xc7, 0xfb,
	0x68, 0x12, 0x8e, 0x50, 0x2d, 0x7f, 0xcd, 0x48, 0x65, 0xd2, 0xb8, 0x0f, 0xa8, 0x14, 0x20, 0xe7,
	0x3a, 0xb3, 0x9e, 0x9e, 0x46, 0x25, 0x17, 0x06, 0xff, 0x82, 0xaa, 0xf3, 0x7b, 0xc5, 0xcf, 0xff,
	0x67, 0x50, 0x9a, 0x87, 0x8f, 0xc3, 0xfc, 0x29, 0xda, 0x9f, 0xfe, 0xfa, 0xc7, 0xdf, 0xbf, 0xad,
	0x7d, 0xd2, 0x26, 0xfe, 0xf4, 0xc4, 0x5f, 0x0a, 0x7d, 0xa7, 0xf2, 0xfb, 0x8c, 0xbd, 0xf2, 0x5e,
	0x9c, 0x6e, 0xfd, 0x5c, 0x5f, 0xfd, 0xdb, 0x87, 0x65, 0xf7, 0xa9, 0x7f, 0xfd, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6d, 0x35, 0xa1, 0x36, 0xa4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MySQLClient is the client API for MySQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MySQLClient interface {
	// AddMySQL adds MySQL Service and starts several Agents.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "mysqld_exporter", and "qan_mysql_perfschema" agents
	// with provided "pmm_agent_id" and other parameters.
	AddMySQL(ctx context.Context, in *AddMySQLRequest, opts ...grpc.CallOption) (*AddMySQLResponse, error)
}

type mySQLClient struct {
	cc grpc.ClientConnInterface
}

func NewMySQLClient(cc grpc.ClientConnInterface) MySQLClient {
	return &mySQLClient{cc}
}

func (c *mySQLClient) AddMySQL(ctx context.Context, in *AddMySQLRequest, opts ...grpc.CallOption) (*AddMySQLResponse, error) {
	out := new(AddMySQLResponse)
	err := c.cc.Invoke(ctx, "/management.MySQL/AddMySQL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MySQLServer is the server API for MySQL service.
type MySQLServer interface {
	// AddMySQL adds MySQL Service and starts several Agents.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "mysqld_exporter", and "qan_mysql_perfschema" agents
	// with provided "pmm_agent_id" and other parameters.
	AddMySQL(context.Context, *AddMySQLRequest) (*AddMySQLResponse, error)
}

// UnimplementedMySQLServer can be embedded to have forward compatible implementations.
type UnimplementedMySQLServer struct {
}

func (*UnimplementedMySQLServer) AddMySQL(ctx context.Context, req *AddMySQLRequest) (*AddMySQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMySQL not implemented")
}

func RegisterMySQLServer(s *grpc.Server, srv MySQLServer) {
	s.RegisterService(&_MySQL_serviceDesc, srv)
}

func _MySQL_AddMySQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMySQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySQLServer).AddMySQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/management.MySQL/AddMySQL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySQLServer).AddMySQL(ctx, req.(*AddMySQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MySQL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "management.MySQL",
	HandlerType: (*MySQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMySQL",
			Handler:    _MySQL_AddMySQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managementpb/mysql.proto",
}
