// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementpb/postgresql.proto

package managementpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	inventorypb "github.com/percona/pmm/api/inventorypb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddPostgreSQLRequest struct {
	// Node identifier on which a service is been running.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Node name on which a service is been running.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Create a new Node with those parameters.
	// Exactly one of these parameters should be present: node_id, node_name, add_node.
	AddNode *AddNodeParams `protobuf:"bytes,3,opt,name=add_node,json=addNode,proto3" json:"add_node,omitempty"`
	// Unique across all Services user-defined name. Required.
	ServiceName string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Node and Service access address (DNS name or IP).
	// Address (and port) or socket is required.
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// Service Access port.
	// Port is required when the address present.
	Port uint32 `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	// Service Access socket.
	// Address (and port) or socket is required.
	Socket string `protobuf:"bytes,18,opt,name=socket,proto3" json:"socket,omitempty"`
	// The "pmm-agent" identifier which should run agents. Required.
	PmmAgentId string `protobuf:"bytes,7,opt,name=pmm_agent_id,json=pmmAgentId,proto3" json:"pmm_agent_id,omitempty"`
	// Environment name.
	Environment string `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	// Cluster name.
	Cluster string `protobuf:"bytes,9,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Replication set name.
	ReplicationSet string `protobuf:"bytes,10,opt,name=replication_set,json=replicationSet,proto3" json:"replication_set,omitempty"`
	// PostgreSQL username for scraping metrics.
	Username string `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	// PostgreSQL password for scraping metrics.
	Password string `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	// If true, adds qan-postgresql-pgstatements-agent for provided service.
	QanPostgresqlPgstatementsAgent bool `protobuf:"varint,13,opt,name=qan_postgresql_pgstatements_agent,json=qanPostgresqlPgstatementsAgent,proto3" json:"qan_postgresql_pgstatements_agent,omitempty"`
	// Custom user-assigned labels for Service.
	CustomLabels map[string]string `protobuf:"bytes,14,rep,name=custom_labels,json=customLabels,proto3" json:"custom_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Skip connection check.
	SkipConnectionCheck bool `protobuf:"varint,15,opt,name=skip_connection_check,json=skipConnectionCheck,proto3" json:"skip_connection_check,omitempty"`
	// Use TLS for database connections.
	Tls bool `protobuf:"varint,16,opt,name=tls,proto3" json:"tls,omitempty"`
	// Skip TLS certificate and hostname validation. Uses sslmode=required instead of verify-full.
	TlsSkipVerify bool `protobuf:"varint,17,opt,name=tls_skip_verify,json=tlsSkipVerify,proto3" json:"tls_skip_verify,omitempty"`
	// enables push model at exporter
	PushModelEnabled     bool     `protobuf:"varint,23,opt,name=push_model_enabled,json=pushModelEnabled,proto3" json:"push_model_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostgreSQLRequest) Reset()         { *m = AddPostgreSQLRequest{} }
func (m *AddPostgreSQLRequest) String() string { return proto.CompactTextString(m) }
func (*AddPostgreSQLRequest) ProtoMessage()    {}
func (*AddPostgreSQLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e72a2ebc60b1270, []int{0}
}

func (m *AddPostgreSQLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostgreSQLRequest.Unmarshal(m, b)
}
func (m *AddPostgreSQLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostgreSQLRequest.Marshal(b, m, deterministic)
}
func (m *AddPostgreSQLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostgreSQLRequest.Merge(m, src)
}
func (m *AddPostgreSQLRequest) XXX_Size() int {
	return xxx_messageInfo_AddPostgreSQLRequest.Size(m)
}
func (m *AddPostgreSQLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostgreSQLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostgreSQLRequest proto.InternalMessageInfo

func (m *AddPostgreSQLRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetAddNode() *AddNodeParams {
	if m != nil {
		return m.AddNode
	}
	return nil
}

func (m *AddPostgreSQLRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AddPostgreSQLRequest) GetSocket() string {
	if m != nil {
		return m.Socket
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetPmmAgentId() string {
	if m != nil {
		return m.PmmAgentId
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetReplicationSet() string {
	if m != nil {
		return m.ReplicationSet
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddPostgreSQLRequest) GetQanPostgresqlPgstatementsAgent() bool {
	if m != nil {
		return m.QanPostgresqlPgstatementsAgent
	}
	return false
}

func (m *AddPostgreSQLRequest) GetCustomLabels() map[string]string {
	if m != nil {
		return m.CustomLabels
	}
	return nil
}

func (m *AddPostgreSQLRequest) GetSkipConnectionCheck() bool {
	if m != nil {
		return m.SkipConnectionCheck
	}
	return false
}

func (m *AddPostgreSQLRequest) GetTls() bool {
	if m != nil {
		return m.Tls
	}
	return false
}

func (m *AddPostgreSQLRequest) GetTlsSkipVerify() bool {
	if m != nil {
		return m.TlsSkipVerify
	}
	return false
}

func (m *AddPostgreSQLRequest) GetPushModelEnabled() bool {
	if m != nil {
		return m.PushModelEnabled
	}
	return false
}

type AddPostgreSQLResponse struct {
	Service                        *inventorypb.PostgreSQLService              `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PostgresExporter               *inventorypb.PostgresExporter               `protobuf:"bytes,2,opt,name=postgres_exporter,json=postgresExporter,proto3" json:"postgres_exporter,omitempty"`
	QanPostgresqlPgstatementsAgent *inventorypb.QANPostgreSQLPgStatementsAgent `protobuf:"bytes,3,opt,name=qan_postgresql_pgstatements_agent,json=qanPostgresqlPgstatementsAgent,proto3" json:"qan_postgresql_pgstatements_agent,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                                    `json:"-"`
	XXX_unrecognized               []byte                                      `json:"-"`
	XXX_sizecache                  int32                                       `json:"-"`
}

func (m *AddPostgreSQLResponse) Reset()         { *m = AddPostgreSQLResponse{} }
func (m *AddPostgreSQLResponse) String() string { return proto.CompactTextString(m) }
func (*AddPostgreSQLResponse) ProtoMessage()    {}
func (*AddPostgreSQLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e72a2ebc60b1270, []int{1}
}

func (m *AddPostgreSQLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostgreSQLResponse.Unmarshal(m, b)
}
func (m *AddPostgreSQLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostgreSQLResponse.Marshal(b, m, deterministic)
}
func (m *AddPostgreSQLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostgreSQLResponse.Merge(m, src)
}
func (m *AddPostgreSQLResponse) XXX_Size() int {
	return xxx_messageInfo_AddPostgreSQLResponse.Size(m)
}
func (m *AddPostgreSQLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostgreSQLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostgreSQLResponse proto.InternalMessageInfo

func (m *AddPostgreSQLResponse) GetService() *inventorypb.PostgreSQLService {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *AddPostgreSQLResponse) GetPostgresExporter() *inventorypb.PostgresExporter {
	if m != nil {
		return m.PostgresExporter
	}
	return nil
}

func (m *AddPostgreSQLResponse) GetQanPostgresqlPgstatementsAgent() *inventorypb.QANPostgreSQLPgStatementsAgent {
	if m != nil {
		return m.QanPostgresqlPgstatementsAgent
	}
	return nil
}

func init() {
	proto.RegisterType((*AddPostgreSQLRequest)(nil), "management.AddPostgreSQLRequest")
	proto.RegisterMapType((map[string]string)(nil), "management.AddPostgreSQLRequest.CustomLabelsEntry")
	proto.RegisterType((*AddPostgreSQLResponse)(nil), "management.AddPostgreSQLResponse")
}

func init() {
	proto.RegisterFile("managementpb/postgresql.proto", fileDescriptor_6e72a2ebc60b1270)
}

var fileDescriptor_6e72a2ebc60b1270 = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6f, 0x23, 0x35,
	0x14, 0xd6, 0xa4, 0xbb, 0x49, 0xea, 0x24, 0x6d, 0x6a, 0x76, 0x59, 0x93, 0xdd, 0x85, 0x6c, 0x0e,
	0x90, 0x45, 0x34, 0x23, 0x02, 0xaa, 0x50, 0x2f, 0x28, 0xad, 0x2a, 0x51, 0xa9, 0x54, 0xe9, 0x44,
	0x02, 0xc4, 0x65, 0xe4, 0x8c, 0x1f, 0xd3, 0x51, 0x66, 0x6c, 0xc7, 0x76, 0x52, 0x72, 0xe1, 0xc0,
	0x19, 0x89, 0x03, 0x3f, 0x89, 0x9f, 0xc0, 0x0f, 0x40, 0x42, 0xfc, 0x10, 0x64, 0xcf, 0x24, 0x93,
	0xb4, 0x12, 0xdd, 0x9b, 0xdf, 0xfb, 0x3e, 0xbf, 0xf7, 0xbd, 0xe7, 0x6f, 0x06, 0xbd, 0xce, 0x28,
	0xa7, 0x31, 0x64, 0xc0, 0x8d, 0x9c, 0xfa, 0x52, 0x68, 0x13, 0x2b, 0xd0, 0xf3, 0x74, 0x20, 0x95,
	0x30, 0x02, 0xa3, 0x12, 0xee, 0x9c, 0xc4, 0x89, 0xb9, 0x5d, 0x4c, 0x07, 0x91, 0xc8, 0xfc, 0xec,
	0x2e, 0x31, 0x33, 0x71, 0xe7, 0xc7, 0xe2, 0xd8, 0x11, 0x8f, 0x97, 0x34, 0x4d, 0x18, 0x35, 0x42,
	0x69, 0x7f, 0x73, 0xcc, 0x6b, 0x74, 0x5e, 0xc5, 0x42, 0xc4, 0x29, 0xf8, 0x54, 0x26, 0x3e, 0xe5,
	0x5c, 0x18, 0x6a, 0x12, 0xc1, 0x75, 0x81, 0x92, 0x84, 0x2f, 0x81, 0x1b, 0xa1, 0x56, 0x72, 0xea,
	0xd3, 0x18, 0xb8, 0x59, 0x23, 0x9d, 0x6d, 0x44, 0x83, 0x5a, 0x26, 0x11, 0x6c, 0xb0, 0x1d, 0xd9,
	0x05, 0x98, 0x63, 0xbd, 0x3f, 0xab, 0xe8, 0xd9, 0x88, 0xb1, 0x71, 0x3e, 0xcb, 0xe4, 0xe6, 0x2a,
	0x80, 0xf9, 0x02, 0xb4, 0xc1, 0x2f, 0x50, 0x8d, 0x0b, 0x06, 0x61, 0xc2, 0x88, 0xd7, 0xf5, 0xfa,
	0xfb, 0x41, 0xd5, 0x86, 0x97, 0x0c, 0xbf, 0x44, 0xfb, 0x0e, 0xe0, 0x34, 0x03, 0x52, 0x71, 0x50,
	0xdd, 0x26, 0xae, 0x69, 0x06, 0xf8, 0x4b, 0x54, 0xa7, 0x8c, 0x85, 0x36, 0x26, 0x7b, 0x5d, 0xaf,
	0xdf, 0x18, 0x7e, 0x30, 0x28, 0xbb, 0x0f, 0x46, 0x8c, 0x5d, 0x0b, 0x06, 0x63, 0xaa, 0x68, 0xa6,
	0x83, 0x1a, 0xcd, 0x43, 0xfc, 0x16, 0x35, 0x0b, 0x55, 0x79, 0xd5, 0x27, 0xb6, 0xea, 0x59, 0xf5,
	0x9f, 0xbf, 0x3f, 0xaa, 0xfc, 0xe0, 0x05, 0x8d, 0x02, 0x73, 0x0d, 0x08, 0xb2, 0xb7, 0x14, 0x68,
	0x4d, 0x9e, 0xba, 0xde, 0xeb, 0x10, 0x63, 0xf4, 0x44, 0x0a, 0x65, 0x48, 0xb5, 0xeb, 0xf5, 0x5b,
	0x81, 0x3b, 0xe3, 0xf7, 0x51, 0x55, 0x8b, 0x68, 0x06, 0x86, 0xe0, 0x7c, 0x86, 0x3c, 0xc2, 0x7d,
	0xd4, 0x94, 0x59, 0x16, 0xba, 0x0d, 0xda, 0x09, 0x6b, 0x3b, 0x0d, 0x91, 0xcc, 0xb2, 0x91, 0x85,
	0x2e, 0x19, 0xee, 0xa2, 0x06, 0xf0, 0x65, 0xa2, 0x04, 0xb7, 0x03, 0x90, 0xba, 0x2b, 0xb3, 0x9d,
	0xb2, 0x8a, 0xa2, 0x74, 0xa1, 0x0d, 0x28, 0xb2, 0x9f, 0x2b, 0x2a, 0x42, 0xfc, 0x09, 0x3a, 0x54,
	0x20, 0xd3, 0x24, 0x72, 0x6f, 0x18, 0x6a, 0x30, 0x04, 0x39, 0xc6, 0xc1, 0x56, 0x7a, 0x02, 0x06,
	0xf7, 0x50, 0x7d, 0xa1, 0x41, 0xb9, 0xd9, 0x1b, 0x3b, 0x52, 0x36, 0x79, 0xdc, 0x41, 0x75, 0x49,
	0xb5, 0xbe, 0x13, 0x8a, 0x91, 0x66, 0xbe, 0xf5, 0x75, 0x8c, 0x2f, 0xd1, 0x9b, 0x39, 0xe5, 0x61,
	0x69, 0xc8, 0x50, 0xc6, 0xda, 0x50, 0xe3, 0x96, 0xae, 0xf3, 0x31, 0x49, 0xab, 0xeb, 0xf5, 0xeb,
	0xc1, 0x87, 0x73, 0xca, 0xc7, 0x1b, 0xde, 0x78, 0x8b, 0xe6, 0x26, 0xc6, 0xdf, 0xa3, 0x56, 0xb4,
	0xd0, 0x46, 0x64, 0x61, 0x4a, 0xa7, 0x90, 0x6a, 0x72, 0xd0, 0xdd, 0xeb, 0x37, 0x86, 0xc3, 0x7b,
	0xaf, 0xf8, 0xc0, 0x2f, 0x83, 0x73, 0x77, 0xeb, 0xca, 0x5d, 0xba, 0xe0, 0x46, 0xad, 0x82, 0x66,
	0xb4, 0x95, 0xc2, 0x43, 0xf4, 0x5c, 0xcf, 0x12, 0x19, 0x46, 0x82, 0x73, 0x88, 0xdc, 0x42, 0xa2,
	0x5b, 0x88, 0x66, 0xe4, 0xd0, 0xe9, 0x7a, 0xcf, 0x82, 0xe7, 0x1b, 0xec, 0xdc, 0x42, 0xb8, 0x8d,
	0xf6, 0x4c, 0xaa, 0x49, 0xdb, 0x31, 0xec, 0x11, 0x7f, 0x8c, 0x0e, 0x4d, 0xaa, 0x43, 0x57, 0x69,
	0x09, 0x2a, 0xf9, 0x69, 0x45, 0x8e, 0x1c, 0xda, 0x32, 0xa9, 0x9e, 0xcc, 0x12, 0xf9, 0x9d, 0x4b,
	0xe2, 0xcf, 0x10, 0x96, 0x0b, 0x7d, 0x1b, 0x66, 0x82, 0x41, 0x1a, 0x02, 0xa7, 0xd3, 0x14, 0x18,
	0x79, 0xe1, 0xa8, 0x6d, 0x8b, 0x7c, 0x6b, 0x81, 0x8b, 0x3c, 0xdf, 0xf9, 0x1a, 0x1d, 0x3d, 0x90,
	0x6f, 0x9b, 0xcf, 0x60, 0x55, 0x98, 0xdf, 0x1e, 0xf1, 0x33, 0xf4, 0x74, 0x49, 0xd3, 0xc5, 0xda,
	0xf5, 0x79, 0x70, 0x5a, 0xf9, 0xca, 0xeb, 0xfd, 0x5e, 0x41, 0xcf, 0xef, 0x6d, 0x45, 0x4b, 0xc1,
	0x35, 0xe0, 0x13, 0x54, 0x2b, 0xec, 0xeb, 0x2a, 0x35, 0x86, 0xaf, 0x06, 0x9b, 0x2f, 0x75, 0x50,
	0xf2, 0x27, 0x39, 0x27, 0x58, 0x93, 0xf1, 0x37, 0xe8, 0x68, 0xfd, 0x9c, 0x21, 0xfc, 0x6c, 0xcd,
	0x0c, 0xca, 0xf5, 0x6d, 0x0c, 0x5f, 0x3e, 0xac, 0xa0, 0x2f, 0x0a, 0x4a, 0xd0, 0x96, 0xf7, 0x32,
	0xd8, 0xbc, 0x8b, 0x39, 0xf2, 0x6f, 0xf5, 0xed, 0x56, 0xe5, 0x9b, 0xd1, 0x75, 0x29, 0x6f, 0x1c,
	0x4f, 0x76, 0x7d, 0xf2, 0x98, 0x8f, 0x86, 0xbf, 0x79, 0x08, 0x95, 0xf7, 0xf1, 0x2f, 0xa8, 0xb5,
	0xb3, 0x1f, 0xdc, 0x7d, 0xcc, 0x50, 0x9d, 0x37, 0xff, 0xc3, 0xc8, 0x97, 0xdb, 0xeb, 0xff, 0xfa,
	0xd7, 0xbf, 0x7f, 0x54, 0x7a, 0xbd, 0xd7, 0xfe, 0xf2, 0x73, 0xbf, 0x64, 0xfb, 0x25, 0xd5, 0x1f,
	0x31, 0x76, 0xea, 0x7d, 0x7a, 0x76, 0xf0, 0x63, 0x73, 0xfb, 0x27, 0x38, 0xad, 0xba, 0xbf, 0xdf,
	0x17, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x8a, 0x55, 0x00, 0xd2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostgreSQLClient is the client API for PostgreSQL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostgreSQLClient interface {
	// AddPostgreSQL adds PostgreSQL Service and starts postgres exporter.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "postgres_exporter" with provided "pmm_agent_id" and other parameters.
	AddPostgreSQL(ctx context.Context, in *AddPostgreSQLRequest, opts ...grpc.CallOption) (*AddPostgreSQLResponse, error)
}

type postgreSQLClient struct {
	cc grpc.ClientConnInterface
}

func NewPostgreSQLClient(cc grpc.ClientConnInterface) PostgreSQLClient {
	return &postgreSQLClient{cc}
}

func (c *postgreSQLClient) AddPostgreSQL(ctx context.Context, in *AddPostgreSQLRequest, opts ...grpc.CallOption) (*AddPostgreSQLResponse, error) {
	out := new(AddPostgreSQLResponse)
	err := c.cc.Invoke(ctx, "/management.PostgreSQL/AddPostgreSQL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostgreSQLServer is the server API for PostgreSQL service.
type PostgreSQLServer interface {
	// AddPostgreSQL adds PostgreSQL Service and starts postgres exporter.
	// It automatically adds a service to inventory, which is running on provided "node_id",
	// then adds "postgres_exporter" with provided "pmm_agent_id" and other parameters.
	AddPostgreSQL(context.Context, *AddPostgreSQLRequest) (*AddPostgreSQLResponse, error)
}

// UnimplementedPostgreSQLServer can be embedded to have forward compatible implementations.
type UnimplementedPostgreSQLServer struct {
}

func (*UnimplementedPostgreSQLServer) AddPostgreSQL(ctx context.Context, req *AddPostgreSQLRequest) (*AddPostgreSQLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPostgreSQL not implemented")
}

func RegisterPostgreSQLServer(s *grpc.Server, srv PostgreSQLServer) {
	s.RegisterService(&_PostgreSQL_serviceDesc, srv)
}

func _PostgreSQL_AddPostgreSQL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostgreSQLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSQLServer).AddPostgreSQL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/management.PostgreSQL/AddPostgreSQL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSQLServer).AddPostgreSQL(ctx, req.(*AddPostgreSQLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostgreSQL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "management.PostgreSQL",
	HandlerType: (*PostgreSQLServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPostgreSQL",
			Handler:    _PostgreSQL_AddPostgreSQL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managementpb/postgresql.proto",
}
